##Matrix and its Operations

In [ ]:
import numpy as np
a = np.array([1,2,3]) #This is 1 x 3 array
a[0]=4
print(a)

[4 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]]) #This is an example of 2x3 matrix
b[0,0]=7
print(b)

[[7 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])#This is an example of square matrix
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
d = np.full((2,2),4)
print(d)

[[4 4]
 [4 4]]


In [ ]:
e = np.eye(2)
print(e)

[[1. 0.]
 [0. 1.]]


In [ ]:
e= np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e)

[1 5 9]


In [ ]:
f = np.empty((0,10))
print(f)

[]


In [ ]:
g = np.zeros((2,2))
print(g)

[[0. 0.]
 [0. 0.]]


In [ ]:
e = np.eye(2)
g = np.zeros((2,2))
print(e)
print(g)
print(e+g) #This is the code to get the summation of matrices e and g
print(e-g) #This is the code to get the difference of matrices e and g
print(g-e)

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[-1.  0.]
 [ 0. -1.]]
