##Matrix and Its Operators

##Python Exercise 2
#Test Content

Create a NumPy program that performs the operations of the given matrices:

1.sum = A +B

2.difference1 = B - A

3.difference2 = A - B

In [2]:
import numpy as np
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])
print(a+b)

[[ 1 -3]
 [ 6  4]]


In [3]:
print(b-a)

[[11 -3]
 [-2  2]]


In [4]:
print(a-b)

[[-11   3]
 [  2  -2]]
